// All meal data for the trip
const MEALS = [
  {
    id: 'wed-lunch',
    day: 'Wednesday',
    dayIndex: 0,
    type: 'Lunch',
    source: '🛣️ Drive-thru or road stop',
    sourceKey: 'drive-thru',
    name: 'Road Lunch',
    description: 'Keep it simple. Don\'t arrive at the rental hungry and depleted. Fast food or a packed cooler sandwich. Non-negotiable fuel stop.',
    nutritionNote: null,
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 11, end: 14 },
  },
  {
    id: 'wed-snack',
    day: 'Wednesday',
    dayIndex: 0,
    type: 'Snack',
    source: '🧊 Cooler',
    sourceKey: 'cooler',
    name: 'Arrival Snack',
    description: 'Chips, drinks, and cut fruit set out on the counter while everyone unloads and settles in. This is arrival energy — keep it casual and low effort. No cooking, no assembly required.',
    nutritionNote: null,
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 15, end: 17 },
  },
  {
    id: 'wed-dinner',
    day: 'Wednesday',
    dayIndex: 0,
    type: 'Dinner',
    source: '🏠 Cook at rental',
    sourceKey: 'cook',
    name: 'Burgers on the Grill',
    description: 'Burgers on the grill. Fast, social, crowd-proof. Set out condiments, tomato slices, avocado. Side of coleslaw mix or sliced avocado and tomato — five minutes, real nutritional value.',
    nutritionNote: 'Do not skip the vegetable side. Coleslaw mix or avocado and tomato. Five minutes, no cooking required.',
    scaleNote: 'This meal scales immediately. If other families arrive Wednesday, this becomes a group cookout. Buy extra patties. Grill format is naturally social and requires zero structural change for a larger group.',
    flex: true,
    flexDescription: 'COOKOUT FLEX — If neighborhood friends are arriving Wednesday and want to eat together, activate this as a group cookout. Just add more patties to the grill. Nothing else changes.',
    locked: false,
    timeWindow: { start: 18, end: 21 },
  },
  {
    id: 'thu-breakfast',
    day: 'Thursday',
    dayIndex: 1,
    type: 'Breakfast',
    source: '🏠 Cook at rental',
    sourceKey: 'cook',
    name: 'Breakfast Tacos + Yogurt Parfait Bar',
    description: 'Breakfast tacos — scrambled eggs, bacon, seasoned beans, HEB ready-to-cook flour tortillas. Set out shredded cheese and salsa. Run the yogurt parfait bar alongside: Costco granola, yogurt cups, and whatever fruit is left from arrival. Teenage girls will eat it if it is sitting there ready to go.',
    nutritionNote: 'Beans add protein and fiber at zero extra effort. Yogurt parfait bar is self-serve — set it out and let it run alongside the tacos.',
    scaleNote: 'Add more eggs and tortillas if other families join. The format handles extra people easily.',
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 7, end: 10 },
  },
  {
    id: 'thu-lunch',
    day: 'Thursday',
    dayIndex: 1,
    type: 'Lunch',
    source: '🏖️ Buy at pool or beach',
    sourceKey: 'pool',
    name: 'Pool / Beach — Fend for Yourselves',
    description: 'Everyone fends for themselves or buys at the pool concession. You do not need to organize or cook this meal. This is a natural social window.',
    nutritionNote: null,
    scaleNote: null,
    flex: true,
    flexDescription: 'SOCIAL FLEX — Easiest flex window of the entire trip. If neighborhood friends are around, everyone just buys their own at the pool. No hosting, no cooking, no coordination required.',
    locked: false,
    timeWindow: { start: 11, end: 14 },
  },
  {
    id: 'thu-snack',
    day: 'Thursday',
    dayIndex: 1,
    type: 'Snack',
    source: '🧊 Beach bag',
    sourceKey: 'cooler',
    name: 'Beach Snack Bag',
    description: 'Pack a dedicated beach bag snack stash that goes to the beach every day. Lead with protein and fruit: yogurt cups, granola, grapes, string cheese, hummus and baby carrots. Put chips alongside as secondary, not primary. This kills the 3pm hungry problem before it starts.',
    nutritionNote: 'Fruit and protein lead every beach snack bag. Chips are secondary, not the anchor.',
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 14, end: 17 },
  },
  {
    id: 'thu-dinner',
    day: 'Thursday',
    dayIndex: 1,
    type: 'Dinner',
    source: '🍽️ Restaurant reservation',
    sourceKey: 'restaurant',
    name: 'Restaurant Dinner — LOCKED',
    description: 'LOCKED. This is the one hard commitment of the trip. No flex, no swap, no cooking. Show up and enjoy it.',
    nutritionNote: null,
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: true,
    timeWindow: { start: 18, end: 21 },
  },
  {
    id: 'fri-breakfast',
    day: 'Friday',
    dayIndex: 2,
    type: 'Breakfast',
    source: '🏠 Cook at rental',
    sourceKey: 'cook',
    name: 'Fruit Toast Bar + Eggs & Beans',
    description: 'Fruit toast bar as the anchor — almond butter on toast or bread, topped with remaining banana, berries, and kiwi. Supplement with eggs and HEB tortillas, beans on the side for anyone wanting a more substantial plate. This is the last morning to use the soft fruit — prioritize it.',
    nutritionNote: 'Last window for bananas and kiwi. Use all remaining soft fruit this morning.',
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 7, end: 10 },
  },
  {
    id: 'fri-lunch',
    day: 'Friday',
    dayIndex: 2,
    type: 'Lunch',
    source: '🧊 Pack it',
    sourceKey: 'cooler',
    name: 'Packed Beach Lunches',
    description: 'Pack sandwiches or wraps at the rental and take them to the beach. Deli meat, cheese, HEB tortillas or sandwich bread, mustard and mayo. 15 minutes to assemble. Add baby carrots, grapes, or a granola bar to each packed lunch. Saves real money over pool concessions for 8 people.',
    nutritionNote: 'Add fruit, carrots, or a granola bar to every packed lunch bag.',
    scaleNote: 'If flex activates and you eat out instead, the deli supplies shift to Saturday morning or extra snacks. Nothing is wasted.',
    flex: true,
    flexDescription: 'EAT OUT FLEX — If neighborhood friends want to grab lunch Friday, skip packing and go. Activate this slot and add a coordination note so both parents know the deli supplies have shifted.',
    locked: false,
    timeWindow: { start: 11, end: 14 },
  },
  {
    id: 'fri-snack',
    day: 'Friday',
    dayIndex: 2,
    type: 'Snack',
    source: '🧊 Beach bag',
    sourceKey: 'cooler',
    name: 'Beach Snack Bag',
    description: 'Same beach bag rotation as Thursday. Replenish whatever ran out. Keep leading with fruit and protein.',
    nutritionNote: null,
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 14, end: 17 },
  },
  {
    id: 'fri-dinner',
    day: 'Friday',
    dayIndex: 2,
    type: 'Dinner',
    source: '🏠 Cook at rental',
    sourceKey: 'cook',
    name: 'Pasta Bar',
    description: 'Pasta bar. Boil a large pot of pasta. Run two sauces: marinara and butter with garlic. Set out parmesan, meatballs or sliced Italian sausage, a big green salad (mixed greens, cherry tomatoes, cucumber), and a loaf of bread. Everyone serves themselves. Cook time under 35 minutes. One pot, minimal cleanup.',
    nutritionNote: 'The green salad is non-negotiable. Do not skip it. Five minutes and it is the entire vegetable component for Friday dinner.',
    scaleNote: 'The easiest meal on the trip to scale. Add another box of pasta and more bread. Handles 12-16 people without any structural change.',
    flex: true,
    flexDescription: 'PIZZA SWAP FLEX — If another family joins and you would rather not cook, deploy the pizza wildcard here and order enough for the full group. All pasta ingredients are non-perishable or travel home easily. Nothing wasted.',
    locked: false,
    timeWindow: { start: 18, end: 21 },
  },
  {
    id: 'sat-breakfast',
    day: 'Saturday',
    dayIndex: 3,
    type: 'Breakfast',
    source: '🧊 Light — cold prep only',
    sourceKey: 'cooler',
    name: 'Cold Breakfast — Pack-Up Morning',
    description: 'Fruit toast bar with whatever almond butter and fruit remains. Yogurt parfaits with Costco granola. Granola bars as backup. Cereal and milk if needed. NO COOKING on pack-up morning. Everything set out cold and self-serve while everyone loads bags and cleans rooms. Goal is fed and out the door, not a meal event.',
    nutritionNote: 'Use all remaining fruit this morning. Nothing perishable should go back in the car.',
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 7, end: 10 },
  },
  {
    id: 'sat-lunch',
    day: 'Saturday',
    dayIndex: 3,
    type: 'Lunch',
    source: '🛣️ Drive-thru or road stop',
    sourceKey: 'drive-thru',
    name: 'Road Lunch — Heading Home',
    description: 'Stop on the way home. You have earned it. No planning required.',
    nutritionNote: null,
    scaleNote: null,
    flex: false,
    flexDescription: null,
    locked: false,
    timeWindow: { start: 11, end: 14 },
  },
];

// Map meal IDs to associated shopping items for flex flagging
const FLEX_MEAL_SHOPPING_MAP = {
  'wed-dinner': ['Burger patties (buy extra if cookout flex likely)', 'Burger buns', 'Shredded cabbage or coleslaw mix (burgers + tacos)'],
  'fri-lunch': ['Deli meat for packed lunches', 'Deli cheese slices'],
  'fri-dinner': ['Pasta — 3 boxes (accounts for group scaling)', 'Marinara sauce — 2 jars', 'Meatballs or Italian sausage for pasta bar', 'Parmesan — block or pre-grated', 'Bread loaf for pasta night', 'Garlic (pasta night)', 'Mixed salad greens (pasta night salad)', 'Cucumber (pasta salad)', 'Cherry tomatoes (pasta salad + tacos)'],
};

const SHOPPING_LIST = [
  {
    store: 'Costco',
    items: [
      { id: 'costco-1', name: 'Eggs — large flat', note: null },
      { id: 'costco-2', name: 'Bacon — enough for one full breakfast taco morning for 8', note: null },
      { id: 'costco-3', name: 'Pumpkin and flaxseed granola — large bag', note: 'Runs across 3 days of breakfast and beach snacks' },
    ],
  },
  {
    store: 'HEB — Bread and Tortillas',
    items: [
      { id: 'heb-bread-1', name: 'HEB ready-to-cook flour tortillas — large pack', note: '⚠️ Double duty: breakfast tacos Thursday + taco dinner Friday' },
      { id: 'heb-bread-2', name: 'Sandwich bread — for fruit toast bar and packed lunches', note: null },
      { id: 'heb-bread-3', name: 'Burger buns', note: null },
      { id: 'heb-bread-4', name: 'Bread loaf for pasta night', note: null },
    ],
  },
  {
    store: 'HEB — Pantry',
    items: [
      { id: 'heb-pantry-1', name: 'Almond butter — one large jar (fruit toast bar, used 2x)', note: null },
      { id: 'heb-pantry-2', name: 'Beans — 2 cans', note: '⚠️ Double duty: breakfast tacos + taco dinner' },
      { id: 'heb-pantry-3', name: 'Pancake mix + syrup (backup breakfast option)', note: null },
      { id: 'heb-pantry-4', name: 'Pasta — 3 boxes (accounts for group scaling)', note: null },
      { id: 'heb-pantry-5', name: 'Marinara sauce — 2 jars', note: null },
      { id: 'heb-pantry-6', name: 'Salsa', note: null },
      { id: 'heb-pantry-7', name: 'Ketchup, mustard, mayo', note: null },
      { id: 'heb-pantry-8', name: 'Butter (cooking + pasta sauce)', note: null },
      { id: 'heb-pantry-9', name: 'Garlic (pasta night)', note: null },
      { id: 'heb-pantry-10', name: 'Olive oil', note: null },
    ],
  },
  {
    store: 'HEB — Dairy and Non-Dairy',
    items: [
      { id: 'heb-dairy-1', name: 'Whole milk', note: '⚠️ Food allergy in group — stock both' },
      { id: 'heb-dairy-2', name: 'Non-dairy milk — oat or almond', note: '⚠️ Confirm allergy specifics' },
      { id: 'heb-dairy-3', name: 'Yogurt — individual cups and/or large tub (runs 3 days)', note: null },
      { id: 'heb-dairy-4', name: 'Parmesan — block or pre-grated', note: null },
      { id: 'heb-dairy-5', name: 'Shredded cheese (tacos + breakfast tacos)', note: null },
      { id: 'heb-dairy-6', name: 'Sour cream', note: null },
      { id: 'heb-dairy-7', name: 'Coffee creamer — dairy version ☕', note: null },
      { id: 'heb-dairy-8', name: 'Coffee creamer — non-dairy version ☕', note: '⚠️ Allergy' },
    ],
  },
  {
    store: 'HEB — Proteins',
    items: [
      { id: 'heb-protein-1', name: 'Burger patties (buy extra if cookout flex likely)', note: null },
      { id: 'heb-protein-2', name: 'Ground beef or chicken for taco dinner', note: null },
      { id: 'heb-protein-3', name: 'Meatballs or Italian sausage for pasta bar', note: null },
      { id: 'heb-protein-4', name: 'Deli meat for packed lunches', note: null },
      { id: 'heb-protein-5', name: 'Deli cheese slices', note: null },
    ],
  },
  {
    store: 'HEB — Produce: USE EARLY',
    storeNote: '⚠️ Buy Tuesday. Use at Thursday and Friday breakfast. Do not let these sit in the cooler past Friday.',
    items: [
      { id: 'heb-early-1', name: 'Bananas', note: '⚠️ Use at Thursday and Friday breakfast — perishable. Do not let them sit in the cooler past Friday.' },
      { id: 'heb-early-2', name: 'Kiwi', note: '⚠️ Use at Thursday and Friday breakfast — perishable. Do not let them sit in the cooler past Friday.' },
    ],
  },
  {
    store: 'HEB — Produce: Hardy',
    items: [
      { id: 'heb-hardy-1', name: 'Watermelon', note: null },
      { id: 'heb-hardy-2', name: 'Grapes', note: null },
      { id: 'heb-hardy-3', name: 'Strawberries', note: null },
      { id: 'heb-hardy-4', name: 'Blueberries', note: null },
      { id: 'heb-hardy-5', name: 'Cherry tomatoes (pasta salad + tacos)', note: null },
      { id: 'heb-hardy-6', name: 'Avocados — 4 to 6', note: null },
      { id: 'heb-hardy-7', name: 'Shredded cabbage or coleslaw mix (burgers + tacos)', note: null },
      { id: 'heb-hardy-8', name: 'Mixed salad greens (pasta night salad)', note: null },
      { id: 'heb-hardy-9', name: 'Baby carrots (beach snack bag)', note: null },
      { id: 'heb-hardy-10', name: 'Cucumber (pasta salad)', note: null },
      { id: 'heb-hardy-11', name: 'Tomatoes (burgers + tacos)', note: null },
      { id: 'heb-hardy-12', name: 'Jalapeños — optional, taco bar', note: null },
    ],
  },
  {
    store: 'HEB — Snacks',
    items: [
      { id: 'heb-snack-1', name: 'String cheese', note: null },
      { id: 'heb-snack-2', name: 'Hummus', note: null },
      { id: 'heb-snack-3', name: 'Nuts — mixed or almonds', note: null },
      { id: 'heb-snack-4', name: 'Granola bars — two boxes (beach snack bag + Saturday breakfast)', note: null },
      { id: 'heb-snack-5', name: 'Chips — buy two bags, one goes fast with teenagers', note: null },
      { id: 'heb-snack-6', name: 'Cereal (Saturday backup breakfast)', note: null },
    ],
  },
  {
    store: 'HEB — Drinks',
    items: [
      { id: 'heb-drink-1', name: 'Flat of water bottles — non-negotiable for beach days', note: null },
      { id: 'heb-drink-2', name: 'Sports drinks — Gatorade or equivalent', note: null },
      { id: 'heb-drink-3', name: 'Sodas', note: null },
      { id: 'heb-drink-4', name: 'Orange juice', note: null },
    ],
  },
  {
    store: 'HOME — Coffee and Kitchen',
    items: [
      { id: 'home-1', name: 'Nespresso machine', note: null },
      { id: 'home-2', name: 'Nespresso pods — enough for 4 mornings, account for guests', note: '☕ CONFIRM what the rental unit has BEFORE packing. If they have a drip machine, bring ground coffee as backup.' },
    ],
  },
];

export { MEALS, SHOPPING_LIST, FLEX_MEAL_SHOPPING_MAP };
